#!/usr/bin/env bash
#Bash script that displays a list of currently running processes
# ps: PIDs for the processes currently on the system
# a: Select all processes
# u: Select all processes on a terminal, including those of other users
# x: Select processes without controlling ttys
# less: allows it to be read one screenful at a time
# -f: Do full-format listing. This option can be combined with 
# many other UNIX-style options to add additional columns.  It
# also causes the command arguments to be printed.  When used with -L
ps -aux -f