#!/usr/bin/env bash
# Shows PID without using ps
# of processes whose name contain the word bash
# pgrep: looking through currently running processes
# -l: see a user's process IDs along with the name of each process
pgrep -l bash
